id: P16A21E23
initial_creation_type: input
source_metadata:
  title: Bodhisatvapiṭaka, BMSC IV, Tibetan
  language: bo
  volumes:
    a089c1cc66bb4dd188a2ac0b0cf8e5ec:
      title: .txt
      base_file: .txt.txt
      work_id: W3CBBF086
  chapter_to_tile: {}
created_at: '2022-03-01T21:19:11.700460'
last_modified_at: '2022-03-01T21:19:11.700466'
